### ISSUE TITLE
V6 hot end problem

### ISSUE THREAD

**Issue by Ouxipi** [VoronDesign/Voron-Stealthburner#25]
V6 CAD files with STL CW2 do not conform to the problem

**Comment by raymondh2** [comment]
Please include more details.

**Comment by wile-e1** [comment]
We are aware of the issue and it has been resolved.  The revised CAD models are going to be included in the next update.  The issue was that a feature in the master toolhead blank model caused features in the downstream model to become broken.......yay parametric CAD.

Thank you got bringing this to our attention.
