### ISSUE TITLE
Carriage Manual S.61 Wrong Length Bolts

### ISSUE THREAD

**Issue by thomasfjen** [VoronDesign/Voron-Stealthburner#62]
![image](https://user-images.githubusercontent.com/47940833/208055699-dbb86d46-7a40-46aa-9e5e-4a82f8dab8c5.png)

Manuals says M3x30, i had to use M3x40. CAD also measures 40mm.

**Comment by jonesuki** [comment]
On my MGN12 X-carriage, I can confirmed that M3x30 SHCS is long enough. I checked the STL files and the actual screw length required is about 27.x mm (because the hex bolt actually "sinked" inside the printed parts.
I discovered this because I accidentally installed M3x40 SHCS and both screws sticked out. The bottom one even triggered the X-endstop a few mm too soon.

**Comment by raymondh2** [comment]
Screws are both 30mm. Manual is correct. 
<img width="247" alt="image" src="https://user-images.githubusercontent.com/10180760/215595057-b6a80402-513d-4ff7-b389-7939b6922deb.png">

**Comment by thomasfjen** [comment]
![grafik](https://user-images.githubusercontent.com/47940833/215596969-5cca4194-d7f7-4e94-9197-80c4330809b6.png)
You guys are correct, i was referring to the switchwire carriage and oversaw that this already covered in the switchwire manual.

**Comment by raymondh2** [comment]
Ah it's the switchwire carriage. We should make note of this in the Stealthburner manual.

**Comment by massis87** [comment]
The Trident manual actually mentions a 40mm bolt, which was so long in my case that it stuck out on the right side. I had to change it to a 30mm.

**Comment by nemgrea** [comment]
https://github.com/VoronDesign/Voron-Stealthburner/pull/88
